

server:
  host: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aa0101
    url: jdbc:mysql://192.168.200.137:3306/hmx?serverTimezone=Asia/Shanghai


#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations:
    classpath: mapper/*.xml

logging:
  file:
    path: /logs